### ISSUE TITLE
OBS not starting after install of LV

### ISSUE THREAD

**Issue by appa561** [obs-ai/obs-localvocal#20]
After reinstalling LocalVocal and attempting to start OBS
[2023-09-18 10-13-47.txt](https://github.com/royshil/obs-localvocal/files/12648837/2023-09-18.10-13-47.txt)

After uninstalling LocalVocal and restarting OBS
[2023-09-18 10-22-29.txt](https://github.com/royshil/obs-localvocal/files/12648846/2023-09-18.10-22-29.txt)

Here is another one from a few days ago...
[2023-09-16 21-51-21.txt](https://github.com/royshil/obs-localvocal/files/12648848/2023-09-16.21-51-21.txt)

**Comment by royshil** [comment]
it looks like the plugin is trying to load the `base.en` model, which doesn't exist by default, only the `tiny.en` model is shipped with the plugin. so when you install, setup with `base`, and then uninstall - reinstall, it looks for `base` (i think)
though if the file doesn't exist it should send an error log msg, and not crash... 🤔  

can you try to make a pristine install and remove all the filter instances?

**Comment by royshil** [comment]
@appa561 did you try resetting the filter to see if the model is the problem?

**Comment by royshil** [comment]
@appa561 Are you still experiencing this problem with the latest builds?

By the way, you asked earlier about translation, so I made a video showcasing translation with openai 
https://youtu.be/Q34LQsx-nlg

**Comment by royshil** [comment]
going to close this issue, since i think it's fixed on master now
