### ISSUE TITLE
Implementation of own fine tuned models

### ISSUE THREAD

**Issue by axelf08** [obs-ai/obs-localvocal#24]
I'm working on ways to fine tune whisper models and would love for an easy way of using them with localvocal. Could localvocal have a folder implemented where I can drop the model file and have it be selectable in the localvocal menu?

**Comment by royshil** [comment]
i will add a "Select model file" option in the dropdown which would open a file search box that you can specify your model

**Comment by royshil** [comment]
implemented in #25

**Comment by royshil** [comment]
@axelf08 can you check the artifacts in #25 to see if the model file selection works for you?
it works for me on my setup

**Comment by axelf08** [comment]
I wasn't able to build it on Linux. I reached the point of where when I added localvocal as a filter it crashed OBS.
Using on windows 10 let me choose a custom model. However the fine tune test models I have gives no output. Choosing a normal model did work fine however.

**Comment by royshil** [comment]
We have an outstanding bug on LLinux in another issues

Check your models with whisper.cpp
If that supports them it should work here since I'm just using whisper.cpp
You can look in the logs to find about the error when trying to load the model. Maybe that will give a clue.
Maybe it loads but doesn't work, and maybe it just doesn't load and you need to look into the ggml conversion.

For me it works with the whisper.cpp models when selected as external files.

**Comment by axelf08** [comment]
So whisper.cpp needs a custom ggml format. I was just trying to use a PyTorch model. There already exists a script for converting in the whisper.cpp project. I just need to rewrite it a bit and it should work.  
https://github.com/ggerganov/whisper.cpp/blob/master/models/convert-pt-to-ggml.py

**Comment by royshil** [comment]
@axelf08 Were you successful in converting models?

**Comment by axelf08** [comment]
Yes, the ones provided by whisper.cpp did the job.

**Comment by axelf08** [comment]
My rewrites were just make it easier to use with my finetune application. I just took the huggingface conversion made it not use argv. I have not touched anything that has to do with the scripts conversion functionality.
Also I was wrong earlier, it was not PyTorch models but Huggingface.

**Comment by royshil** [comment]
so you were successful in conversion and loading it on the plugin?

**Comment by axelf08** [comment]
Yes. The plugin is working and gives me a transcription when I record. Everything has been working smoothly for me with it!

**Comment by royshil** [comment]
alright very cool!
would you mind sharing the commands you used to convert your models?
i'd like to record a tutorial on how to do it

**Comment by royshil** [comment]
going to close this issue but @axelf08 get in touch re the fine tuned models
