### ISSUE TITLE
Problem with Russian language

### ISSUE THREAD

**Issue by Nekaras-alt** [obs-ai/obs-localvocal#27]
Good day to you. Thanks a lot for the plugin. But he has a problem. It does not work in Russian at the moment. Apparently there is a problem with Cyrillic.

_The essence of the problem:_
When you speak in Russian, subtitles are printed in the OBS itself with the signs "???". This problem is independent of the Whisper Model.
An interesting point: If you check the "translate" box, the text translates into English and everything works as it should.
If you try to output to the ".txt" format in the Subtitle Output, it will also output incomprehensible text.
![image_677](https://github.com/royshil/obs-localvocal/assets/56386827/c952af50-3a70-4908-9cb6-54ea10e77627)
![image_678](https://github.com/royshil/obs-localvocal/assets/56386827/4f392b54-83d9-4b61-b3bd-3836577ba38f)
![image_679](https://github.com/royshil/obs-localvocal/assets/56386827/9fcb69f5-f7a8-4696-a84e-b02f75e0ecd2)

**Comment by klasadoroty** [comment]
Hi,
We tested and ... this plugin works reasonably correctly only with English. Russian ... Polish. completely useless.
English - satisfactorily.That is, the plugin useful for English-language transmissions, only.
.. pity.

**Comment by royshil** [comment]
For Russian I suggest using the bigger models like "base" or even "small". And obviously not the ".en" flavor which is only English.

Big models **will** require acceleration hardware like GPU. The CPU will be too slow.

I have also added the option to use any external Whisper.cpp model.
So if you can find a Russian whisper model that would work probably a whole lot better.
_There must be such models in availability..._

**Comment by royshil** [comment]
For example this model https://huggingface.co/lorenzoncina/whisper-small-ru is a "small" fine tuned only for Russian
It needs to be converted to GGML/GGUF
But then can be loaded to OBS LocalVocal as external model
This will likely give you far better results...

**Comment by royshil** [comment]
There are in fact dozens of Russian fine tuned models on hugging face https://huggingface.co/models?sort=trending&search=Whisper+ru

I might add a guide on how to add your own models to LocalVocal... That will make for a cool tutorial.

**Comment by klasadoroty** [comment]
'I might add a guide on how to add your own models to LocalVocal... That will make for a cool tutorial.' - do it!!!

**Comment by royshil** [comment]
@klasadoroty @Nekaras-alt can yall please test #31 ?
i've fixed Russian on Windows, after i was able to reproduce the bug
it seems like a bug in Whisper.cpp's vocabulary...

**Comment by royshil** [comment]
closing this issue, as i think it's fixed
