### ISSUE TITLE
Install instructions for source are too messy

### ISSUE THREAD

**Issue by alkaris2** [obs-ai/obs-localvocal#30]
The way you detail the build and install instructions are all over the place, and none of the scripts that is mentioned in the README.md file do not exist anywhere from downloaded Releases page, the archive created does not have these anywhere.  So when you say;

    Use the CI scripts again
    
    `$ ./.github/scripts/build-linux.sh`

just where exactly is this so-called script that it mentions here? Because they certainly do not exist within the download source archive.

![image](https://github.com/obs-ai/obs-localvocal/assets/73155407/5c833cfa-0327-4678-bc9a-eddad85d6114)

The directory `.github/scripts` simply doesn't exist here as mentioned. Unless they were moved to a different directory and the README wasn't updated to reflect this. The only thing that does come remotely close to this directory is; `vendor/curl/scripts` but even there the thing mentioned doesn't exist here either. Looking through the entire README doesn't provide clear enough details on what's what. Normally when people detail install instructions it's as simple as;

```yaml
|| Download source archive
   |
    \ Extract archive
         |
          \ $ mkdir build && cd build
              |
               \ $ cmake .. && make install
```

While the above typically would do what you want, it won't actually work when you run the build process like that with this plugin since cmake can't determine where the source files are at, and `cmake/common/bootstrap.cmake` points out that in-source builds are not supported, and needs to have two options specified `-S  <SOURCE_DIRECTORY>` and `-B <BUILD_DIRECTORY>` and so with the current set of instruction laid out in the README is basically useless and points to something that doesn't exist. Unusable really to someone who wants to build this plugin from source only to find the details written aren't available within the source files itself.

**Comment by royshil** [comment]
Thanks for the detailed feedback @alkaris2 ! I appreciate your testing the build on Linux, and taking the time to write such a methodical issue.

very strange that the Releases archive doesn't include the `.github` folder... I will check, maybe it's excluded specifically.
However you definitely get the `.github` folder with the build scripts if you `git clone` (which is what I do, and I get it)

**Comment by royshil** [comment]
i've added the `.github` folder to the linux zip in #36

**Comment by royshil** [comment]
closing due to lack of interest
