### ISSUE TITLE
Transcription continues even when source is muted

### ISSUE THREAD

**Issue by Ceralor** [obs-ai/obs-localvocal#34]
Problem: LocalVocal transcribes audio it hears even when the audio source is muted.

Expectation: LocalVocal ceases transcription when source is muted.

Steps to reproduce: Mute the microphone and keep talking anyway.

I know above is a bit silly, but it's a very unexpected issue, which sucks because I really like this project so far.

**Comment by royshil** [comment]
implemented in #36

**Comment by royshil** [comment]
@Ceralor please test the artifacts in https://github.com/obs-ai/obs-localvocal/actions/runs/6442663172 it should be implemented

**Comment by Ceralor** [comment]
Worked properly! However, now it always outputs `[blank_audio]` with VAD off or `[skip]` with it on (and sometimes vice versa) when I'm not saying anything.

As an aside, are the configuration options documented anywhere? It'd be very cool to have a better understanding of the terms involved.

**Comment by royshil** [comment]
if there's no VAD then it your audio to Whisper even if there's no speaking, and Whisper returns [blank_audio] as an output
really VAD should be on, to conserve computation resources.

the config options for Whisper are probably best documented on the whisper repos e.g . https://github.com/ggerganov/whisper.cpp and https://github.com/openai/whisper/
