### ISSUE TITLE
Option to output to SRT

### ISSUE THREAD

**Issue by Ceralor** [obs-ai/obs-localvocal#35]
As it says on the tin, it'd be great to be able to output to an SRT file when recording. I'm not sure if OBS is capable of embedding them in an MKV but that'd be solid too, but just an SRT would be very helpful.

**Comment by royshil** [comment]
this is a great suggestion that's not very hard to implement!

**Comment by royshil** [comment]
implemented in #36

**Comment by royshil** [comment]
@Ceralor would you be able to test the artifacts in https://github.com/obs-ai/obs-localvocal/actions/runs/6442663172 to see if ti works for you?

**Comment by Ceralor** [comment]
Worked! It'd be neat if it could somehow write with the same filename as the video output automatically to avoid requiring configuring that for SRT format, but optional entirely I know.
