### ISSUE TITLE
Do you need pre-built libcurl for every platform?

### ISSUE THREAD

**Issue by umireon** [obs-ai/obs-localvocal#40]
I can create a repository to host pre-built libcurl as OpenCV.

**Comment by royshil** [comment]
@umireon do you have an update on this?

**Comment by umireon** [comment]
I will have time to tackle this next week.

**Comment by royshil** [comment]
> I will have time to tackle this next week.

@umireon I already made it https://github.com/obs-ai/obs-ai-libcurl-dep

**Comment by umireon** [comment]
Feel free to ask me for helps.

**Comment by royshil** [comment]
Looks like the build in the dep repo is solid
Can you take a crack at integration of the binary to this repo cmake builds? @umireon 
🙏

**Comment by umireon** [comment]
Did you removed the release on https://github.com/obs-ai/obs-ai-libcurl-dep?

**Comment by royshil** [comment]
@umireon i just didn't publish the release
bt it's published now
