### ISSUE TITLE
Possible UTF-8 problems

### ISSUE THREAD

**Issue by ASchneiderBR** [obs-ai/obs-localvocal#41]
Hello, first of all, thanks for creating this great tool, really appreciate it.

I just installed the latest version and noticed that there are still problems with foreign characters rendering:

![image](https://github.com/obs-ai/obs-localvocal/assets/25224882/c80417ec-8918-4031-b6d6-35d83342bfa2)

Characters like Ç, É, Ã and so on.

I'm trying to use it with Portuguese language.

Thank you.

**Comment by royshil** [comment]
This is interesting. I'll try to recreate the problem in order to fix it

**Comment by klasadoroty** [comment]
I confirm the same with the Polish language.
Can I find somewhere information /step by step/ - how to download and implement the library for Polish language?
Of course, it also applies to other languages.
Can anyone help?
Thanks

**Comment by royshil** [comment]
i'm investigating now

**Comment by royshil** [comment]
@ASchneiderBR @klasadoroty possible fix in #42 
can you test the binaries when they come out?

**Comment by ASchneiderBR** [comment]
Hello @royshil, it seems it has been fixed:

![image](https://github.com/obs-ai/obs-localvocal/assets/25224882/1326c95e-3184-49be-a5e8-296e62d242de)

Thank you very much!

**Comment by royshil** [comment]
boom! 💥  i like it
i will merge and a release will go out soon
thanks for testing 🙏

**Comment by royshil** [comment]
implemented in #42

**Comment by klasadoroty** [comment]
ok, but.. Polish language - no change... characters do not display.... 
zacząć - zacz
![Zrzut ekranu 2023-10-17 o 21 59 14](https://github.com/obs-ai/obs-localvocal/assets/132354497/9030e2e9-a260-417a-874a-fd63f932e0ec)

**Comment by royshil** [comment]
@klasadoroty  Are you using the builds from the PR or the release version?
The fix is in the PR builds

I was able to see Polish letters in my testing
I made a YT Live where I tested it

https://www.youtube.com/live/x7r5zIEu6MA?si=zqolk8d987FOy-OQ

Look towards the end

**Comment by klasadoroty** [comment]
in text area .. it is ok.
but 'stream captions' .. not

**Comment by royshil** [comment]
@klasadoroty 
The captions are distorted in the stream?
Ok I think I know where the problem is
I can fix it today
Look out for another PR

**Comment by royshil** [comment]
@klasadoroty i'm unable to find a glaring bug
can you share a screenshot of where the problem manifests for you? 🙏

**Comment by klasadoroty** [comment]
up - open captions
down - closed captions
![Zrzut ekranu 2023-10-19 o 17 59 52](https://github.com/obs-ai/obs-localvocal/assets/132354497/23ca4b52-6627-4bee-8562-361268c5f1a2)
many characters/letters missing
mostly other characters , like: ś ć ą ę etc.

**Comment by klasadoroty** [comment]
english:
up - open captions
down - closed captions
![Zrzut ekranu 2023-10-19 o 18 23 53](https://github.com/obs-ai/obs-localvocal/assets/132354497/58e35032-7614-4e0a-9f91-89fe4600538d)

**Comment by klasadoroty** [comment]
one explanation:
open captions - we do it at Google
it's not your job :) /external/
